// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: StressTestingOuterRpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 启动测试
type StartTestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerHosts string `protobuf:"bytes,1,opt,name=serverHosts,proto3" json:"serverHosts,omitempty"`  //服务器地址，多个用逗号隔开
	TestType    int32  `protobuf:"varint,2,opt,name=testType,proto3" json:"testType,omitempty"`       //测试类型  0模拟测试，测试slots对应slots的id
	PlayerCount int32  `protobuf:"varint,3,opt,name=playerCount,proto3" json:"playerCount,omitempty"` //压力测试最大玩家数
	SpawnRate   int32  `protobuf:"varint,4,opt,name=spawnRate,proto3" json:"spawnRate,omitempty"`     //玩家增加频率  users started/second
}

func (x *StartTestRequest) Reset() {
	*x = StartTestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StressTestingOuterRpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTestRequest) ProtoMessage() {}

func (x *StartTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_StressTestingOuterRpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTestRequest.ProtoReflect.Descriptor instead.
func (*StartTestRequest) Descriptor() ([]byte, []int) {
	return file_StressTestingOuterRpc_proto_rawDescGZIP(), []int{0}
}

func (x *StartTestRequest) GetServerHosts() string {
	if x != nil {
		return x.ServerHosts
	}
	return ""
}

func (x *StartTestRequest) GetTestType() int32 {
	if x != nil {
		return x.TestType
	}
	return 0
}

func (x *StartTestRequest) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *StartTestRequest) GetSpawnRate() int32 {
	if x != nil {
		return x.SpawnRate
	}
	return 0
}

// 启动测试
type StartTestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` //0成功，1服务器正在运行中，2非master节点,3 url地址错误，4 请求人数错误,5测试类型错误
	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`  //返回结果
}

func (x *StartTestResponse) Reset() {
	*x = StartTestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StressTestingOuterRpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTestResponse) ProtoMessage() {}

func (x *StartTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_StressTestingOuterRpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTestResponse.ProtoReflect.Descriptor instead.
func (*StartTestResponse) Descriptor() ([]byte, []int) {
	return file_StressTestingOuterRpc_proto_rawDescGZIP(), []int{1}
}

func (x *StartTestResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *StartTestResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// 停止测试
type StopTestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopTestRequest) Reset() {
	*x = StopTestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StressTestingOuterRpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTestRequest) ProtoMessage() {}

func (x *StopTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_StressTestingOuterRpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTestRequest.ProtoReflect.Descriptor instead.
func (*StopTestRequest) Descriptor() ([]byte, []int) {
	return file_StressTestingOuterRpc_proto_rawDescGZIP(), []int{2}
}

// 停止测试
type StopTestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` //0成功
}

func (x *StopTestResponse) Reset() {
	*x = StopTestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StressTestingOuterRpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTestResponse) ProtoMessage() {}

func (x *StopTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_StressTestingOuterRpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTestResponse.ProtoReflect.Descriptor instead.
func (*StopTestResponse) Descriptor() ([]byte, []int) {
	return file_StressTestingOuterRpc_proto_rawDescGZIP(), []int{3}
}

func (x *StopTestResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 请求消息接口统计信息
type RequestInterfaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestInterfaceRequest) Reset() {
	*x = RequestInterfaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StressTestingOuterRpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInterfaceRequest) ProtoMessage() {}

func (x *RequestInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_StressTestingOuterRpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInterfaceRequest.ProtoReflect.Descriptor instead.
func (*RequestInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_StressTestingOuterRpc_proto_rawDescGZIP(), []int{4}
}

// 请求消息接口统计信息
type RequestInterfaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InterfaceInfo []*RequestInterfaceResponse_MessageInterfaceInfo `protobuf:"bytes,1,rep,name=interfaceInfo,proto3" json:"interfaceInfo,omitempty"` //接口信息
}

func (x *RequestInterfaceResponse) Reset() {
	*x = RequestInterfaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StressTestingOuterRpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestInterfaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInterfaceResponse) ProtoMessage() {}

func (x *RequestInterfaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_StressTestingOuterRpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInterfaceResponse.ProtoReflect.Descriptor instead.
func (*RequestInterfaceResponse) Descriptor() ([]byte, []int) {
	return file_StressTestingOuterRpc_proto_rawDescGZIP(), []int{5}
}

func (x *RequestInterfaceResponse) GetInterfaceInfo() []*RequestInterfaceResponse_MessageInterfaceInfo {
	if x != nil {
		return x.InterfaceInfo
	}
	return nil
}

// 主推消息接口统计信息
type PushInterfaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PushInterfaceRequest) Reset() {
	*x = PushInterfaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StressTestingOuterRpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushInterfaceRequest) ProtoMessage() {}

func (x *PushInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_StressTestingOuterRpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushInterfaceRequest.ProtoReflect.Descriptor instead.
func (*PushInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_StressTestingOuterRpc_proto_rawDescGZIP(), []int{6}
}

// 主推消息接口统计信息
type PushInterfaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InterfaceInfo []*PushInterfaceResponse_MessageInterfaceInfo `protobuf:"bytes,1,rep,name=interfaceInfo,proto3" json:"interfaceInfo,omitempty"` //接口信息
}

func (x *PushInterfaceResponse) Reset() {
	*x = PushInterfaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StressTestingOuterRpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushInterfaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushInterfaceResponse) ProtoMessage() {}

func (x *PushInterfaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_StressTestingOuterRpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushInterfaceResponse.ProtoReflect.Descriptor instead.
func (*PushInterfaceResponse) Descriptor() ([]byte, []int) {
	return file_StressTestingOuterRpc_proto_rawDescGZIP(), []int{7}
}

func (x *PushInterfaceResponse) GetInterfaceInfo() []*PushInterfaceResponse_MessageInterfaceInfo {
	if x != nil {
		return x.InterfaceInfo
	}
	return nil
}

// 统计日志
type StatisticsLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatisticsLogRequest) Reset() {
	*x = StatisticsLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StressTestingOuterRpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsLogRequest) ProtoMessage() {}

func (x *StatisticsLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_StressTestingOuterRpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsLogRequest.ProtoReflect.Descriptor instead.
func (*StatisticsLogRequest) Descriptor() ([]byte, []int) {
	return file_StressTestingOuterRpc_proto_rawDescGZIP(), []int{8}
}

// 统计日志
type StatisticsLogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       int32         `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`            //状态 0空闲，1压测中
	StatisticLog *StatisticLog `protobuf:"bytes,2,opt,name=statisticLog,proto3" json:"statisticLog,omitempty"` //统计日志
}

func (x *StatisticsLogResponse) Reset() {
	*x = StatisticsLogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StressTestingOuterRpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsLogResponse) ProtoMessage() {}

func (x *StatisticsLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_StressTestingOuterRpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsLogResponse.ProtoReflect.Descriptor instead.
func (*StatisticsLogResponse) Descriptor() ([]byte, []int) {
	return file_StressTestingOuterRpc_proto_rawDescGZIP(), []int{9}
}

func (x *StatisticsLogResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *StatisticsLogResponse) GetStatisticLog() *StatisticLog {
	if x != nil {
		return x.StatisticLog
	}
	return nil
}

// 统计日志 (根据时间线上)
type StatisticLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp        int32   `protobuf:"varint,1,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`                 //日志时间戳 s
	Rps              float32 `protobuf:"fixed32,2,opt,name=rps,proto3" json:"rps,omitempty"`                            //每秒请求数
	FailRps          float32 `protobuf:"fixed32,3,opt,name=failRps,proto3" json:"failRps,omitempty"`                    //每秒失败数
	ResponseTime     int32   `protobuf:"varint,4,opt,name=responseTime,proto3" json:"responseTime,omitempty"`           //平均反应时间
	PlayerCount      int32   `protobuf:"varint,5,opt,name=playerCount,proto3" json:"playerCount,omitempty"`             //当前用户数
	PushRps          float32 `protobuf:"fixed32,6,opt,name=pushRps,proto3" json:"pushRps,omitempty"`                    //推送rps
	RequestBytes     float32 `protobuf:"fixed32,7,opt,name=requestBytes,proto3" json:"requestBytes,omitempty"`          //总请求流量
	ResponseBytes    float32 `protobuf:"fixed32,8,opt,name=responseBytes,proto3" json:"responseBytes,omitempty"`        //总返回流量 M
	RequestByteRate  float32 `protobuf:"fixed32,9,opt,name=requestByteRate,proto3" json:"requestByteRate,omitempty"`    //请求流量频率 m/s
	ResponseByteRate float32 `protobuf:"fixed32,10,opt,name=responseByteRate,proto3" json:"responseByteRate,omitempty"` //返回流量频率 m/s
	RequestCount     int32   `protobuf:"varint,11,opt,name=requestCount,proto3" json:"requestCount,omitempty"`          //总请求数
	PushCount        int32   `protobuf:"varint,12,opt,name=pushCount,proto3" json:"pushCount,omitempty"`                //总推送数
	FailCount        int32   `protobuf:"varint,13,opt,name=failCount,proto3" json:"failCount,omitempty"`                //总失败数
	CoverRate        float32 `protobuf:"fixed32,14,opt,name=coverRate,proto3" json:"coverRate,omitempty"`               //消息测试覆盖率
}

func (x *StatisticLog) Reset() {
	*x = StatisticLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StressTestingOuterRpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticLog) ProtoMessage() {}

func (x *StatisticLog) ProtoReflect() protoreflect.Message {
	mi := &file_StressTestingOuterRpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticLog.ProtoReflect.Descriptor instead.
func (*StatisticLog) Descriptor() ([]byte, []int) {
	return file_StressTestingOuterRpc_proto_rawDescGZIP(), []int{10}
}

func (x *StatisticLog) GetTimeStamp() int32 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *StatisticLog) GetRps() float32 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *StatisticLog) GetFailRps() float32 {
	if x != nil {
		return x.FailRps
	}
	return 0
}

func (x *StatisticLog) GetResponseTime() int32 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

func (x *StatisticLog) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *StatisticLog) GetPushRps() float32 {
	if x != nil {
		return x.PushRps
	}
	return 0
}

func (x *StatisticLog) GetRequestBytes() float32 {
	if x != nil {
		return x.RequestBytes
	}
	return 0
}

func (x *StatisticLog) GetResponseBytes() float32 {
	if x != nil {
		return x.ResponseBytes
	}
	return 0
}

func (x *StatisticLog) GetRequestByteRate() float32 {
	if x != nil {
		return x.RequestByteRate
	}
	return 0
}

func (x *StatisticLog) GetResponseByteRate() float32 {
	if x != nil {
		return x.ResponseByteRate
	}
	return 0
}

func (x *StatisticLog) GetRequestCount() int32 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *StatisticLog) GetPushCount() int32 {
	if x != nil {
		return x.PushCount
	}
	return 0
}

func (x *StatisticLog) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *StatisticLog) GetCoverRate() float32 {
	if x != nil {
		return x.CoverRate
	}
	return 0
}

// 机器信息查询
type WorkerServerInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WorkerServerInfoRequest) Reset() {
	*x = WorkerServerInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StressTestingOuterRpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerServerInfoRequest) ProtoMessage() {}

func (x *WorkerServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_StressTestingOuterRpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerServerInfoRequest.ProtoReflect.Descriptor instead.
func (*WorkerServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_StressTestingOuterRpc_proto_rawDescGZIP(), []int{11}
}

// 机器信息查询
type WorkerServerInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerServer []*WorkerServerInfoResponse_WorkerServerInfo `protobuf:"bytes,1,rep,name=workerServer,proto3" json:"workerServer,omitempty"` //服务器主机信息
}

func (x *WorkerServerInfoResponse) Reset() {
	*x = WorkerServerInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StressTestingOuterRpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerServerInfoResponse) ProtoMessage() {}

func (x *WorkerServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_StressTestingOuterRpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerServerInfoResponse.ProtoReflect.Descriptor instead.
func (*WorkerServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_StressTestingOuterRpc_proto_rawDescGZIP(), []int{12}
}

func (x *WorkerServerInfoResponse) GetWorkerServer() []*WorkerServerInfoResponse_WorkerServerInfo {
	if x != nil {
		return x.WorkerServer
	}
	return nil
}

// 消息接口信息
type RequestInterfaceResponse_MessageInterfaceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageName     string  `protobuf:"bytes,1,opt,name=messageName,proto3" json:"messageName,omitempty"`           //消息名称
	RequestCount    int32   `protobuf:"varint,2,opt,name=requestCount,proto3" json:"requestCount,omitempty"`        //请求次数
	FailCount       int32   `protobuf:"varint,3,opt,name=failCount,proto3" json:"failCount,omitempty"`              //失败次数
	DelayAverage    int32   `protobuf:"varint,4,opt,name=delayAverage,proto3" json:"delayAverage,omitempty"`        //平均延迟 ms
	DelayMin        int32   `protobuf:"varint,5,opt,name=delayMin,proto3" json:"delayMin,omitempty"`                //最小延迟 ms
	DelayMax        int32   `protobuf:"varint,6,opt,name=delayMax,proto3" json:"delayMax,omitempty"`                //最大延迟 ms
	SizeAverage     int32   `protobuf:"varint,7,opt,name=sizeAverage,proto3" json:"sizeAverage,omitempty"`          //平均大小 bytes
	Rps             float32 `protobuf:"fixed32,8,opt,name=rps,proto3" json:"rps,omitempty"`                         //每秒请求次数
	FailSecondCount float32 `protobuf:"fixed32,9,opt,name=failSecondCount,proto3" json:"failSecondCount,omitempty"` //每秒失败次数
	MessageId       int32   `protobuf:"varint,10,opt,name=messageId,proto3" json:"messageId,omitempty"`             //消息id
}

func (x *RequestInterfaceResponse_MessageInterfaceInfo) Reset() {
	*x = RequestInterfaceResponse_MessageInterfaceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StressTestingOuterRpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestInterfaceResponse_MessageInterfaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInterfaceResponse_MessageInterfaceInfo) ProtoMessage() {}

func (x *RequestInterfaceResponse_MessageInterfaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_StressTestingOuterRpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInterfaceResponse_MessageInterfaceInfo.ProtoReflect.Descriptor instead.
func (*RequestInterfaceResponse_MessageInterfaceInfo) Descriptor() ([]byte, []int) {
	return file_StressTestingOuterRpc_proto_rawDescGZIP(), []int{5, 0}
}

func (x *RequestInterfaceResponse_MessageInterfaceInfo) GetMessageName() string {
	if x != nil {
		return x.MessageName
	}
	return ""
}

func (x *RequestInterfaceResponse_MessageInterfaceInfo) GetRequestCount() int32 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *RequestInterfaceResponse_MessageInterfaceInfo) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *RequestInterfaceResponse_MessageInterfaceInfo) GetDelayAverage() int32 {
	if x != nil {
		return x.DelayAverage
	}
	return 0
}

func (x *RequestInterfaceResponse_MessageInterfaceInfo) GetDelayMin() int32 {
	if x != nil {
		return x.DelayMin
	}
	return 0
}

func (x *RequestInterfaceResponse_MessageInterfaceInfo) GetDelayMax() int32 {
	if x != nil {
		return x.DelayMax
	}
	return 0
}

func (x *RequestInterfaceResponse_MessageInterfaceInfo) GetSizeAverage() int32 {
	if x != nil {
		return x.SizeAverage
	}
	return 0
}

func (x *RequestInterfaceResponse_MessageInterfaceInfo) GetRps() float32 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *RequestInterfaceResponse_MessageInterfaceInfo) GetFailSecondCount() float32 {
	if x != nil {
		return x.FailSecondCount
	}
	return 0
}

func (x *RequestInterfaceResponse_MessageInterfaceInfo) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

// 消息接口信息
type PushInterfaceResponse_MessageInterfaceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageName string  `protobuf:"bytes,1,opt,name=messageName,proto3" json:"messageName,omitempty"`  //消息名称
	Count       int32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`             //推送次数
	MessageId   int32   `protobuf:"varint,3,opt,name=messageId,proto3" json:"messageId,omitempty"`     //消息id
	SizeAverage int32   `protobuf:"varint,7,opt,name=sizeAverage,proto3" json:"sizeAverage,omitempty"` //平均大小 bytes
	Rps         float32 `protobuf:"fixed32,8,opt,name=rps,proto3" json:"rps,omitempty"`                //每秒推送次数
}

func (x *PushInterfaceResponse_MessageInterfaceInfo) Reset() {
	*x = PushInterfaceResponse_MessageInterfaceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StressTestingOuterRpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushInterfaceResponse_MessageInterfaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushInterfaceResponse_MessageInterfaceInfo) ProtoMessage() {}

func (x *PushInterfaceResponse_MessageInterfaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_StressTestingOuterRpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushInterfaceResponse_MessageInterfaceInfo.ProtoReflect.Descriptor instead.
func (*PushInterfaceResponse_MessageInterfaceInfo) Descriptor() ([]byte, []int) {
	return file_StressTestingOuterRpc_proto_rawDescGZIP(), []int{7, 0}
}

func (x *PushInterfaceResponse_MessageInterfaceInfo) GetMessageName() string {
	if x != nil {
		return x.MessageName
	}
	return ""
}

func (x *PushInterfaceResponse_MessageInterfaceInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PushInterfaceResponse_MessageInterfaceInfo) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *PushInterfaceResponse_MessageInterfaceInfo) GetSizeAverage() int32 {
	if x != nil {
		return x.SizeAverage
	}
	return 0
}

func (x *PushInterfaceResponse_MessageInterfaceInfo) GetRps() float32 {
	if x != nil {
		return x.Rps
	}
	return 0
}

// 工作服务器信息
type WorkerServerInfoResponse_WorkerServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                //名称
	RpcHost     string  `protobuf:"bytes,2,opt,name=rpcHost,proto3" json:"rpcHost,omitempty"`          //rpc地址
	CpuRate     float64 `protobuf:"fixed64,3,opt,name=cpuRate,proto3" json:"cpuRate,omitempty"`        //CPU使用率
	MemorySize  int32   `protobuf:"varint,4,opt,name=memorySize,proto3" json:"memorySize,omitempty"`   //内存使用大小
	PlayerCount int32   `protobuf:"varint,5,opt,name=playerCount,proto3" json:"playerCount,omitempty"` //运行玩家数
}

func (x *WorkerServerInfoResponse_WorkerServerInfo) Reset() {
	*x = WorkerServerInfoResponse_WorkerServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StressTestingOuterRpc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerServerInfoResponse_WorkerServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerServerInfoResponse_WorkerServerInfo) ProtoMessage() {}

func (x *WorkerServerInfoResponse_WorkerServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_StressTestingOuterRpc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerServerInfoResponse_WorkerServerInfo.ProtoReflect.Descriptor instead.
func (*WorkerServerInfoResponse_WorkerServerInfo) Descriptor() ([]byte, []int) {
	return file_StressTestingOuterRpc_proto_rawDescGZIP(), []int{12, 0}
}

func (x *WorkerServerInfoResponse_WorkerServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkerServerInfoResponse_WorkerServerInfo) GetRpcHost() string {
	if x != nil {
		return x.RpcHost
	}
	return ""
}

func (x *WorkerServerInfoResponse_WorkerServerInfo) GetCpuRate() float64 {
	if x != nil {
		return x.CpuRate
	}
	return 0
}

func (x *WorkerServerInfoResponse_WorkerServerInfo) GetMemorySize() int32 {
	if x != nil {
		return x.MemorySize
	}
	return 0
}

func (x *WorkerServerInfoResponse_WorkerServerInfo) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

var File_StressTestingOuterRpc_proto protoreflect.FileDescriptor

var file_StressTestingOuterRpc_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x53, 0x74, 0x72, 0x65, 0x73, 0x73, 0x54, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4f,
	0x75, 0x74, 0x65, 0x72, 0x52, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01,
	0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48, 0x6f, 0x73, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48,
	0x6f, 0x73, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x61, 0x74, 0x65,
	0x22, 0x43, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x70, 0x54, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x70,
	0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0xc5, 0x03, 0x0a, 0x18, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x0d,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x1a, 0xd2, 0x02, 0x0a, 0x14, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x41, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x69, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x69, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x61, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x61, 0x78, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x69, 0x7a, 0x65, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x73, 0x69, 0x7a, 0x65, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x70, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x72, 0x70, 0x73, 0x12,
	0x28, 0x0a, 0x0f, 0x66, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0f, 0x66, 0x61, 0x69, 0x6c, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x50, 0x75, 0x73, 0x68, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x8d, 0x02, 0x0a, 0x15, 0x50, 0x75, 0x73, 0x68, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0d, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2b, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0xa0, 0x01, 0x0a,
	0x14, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x69, 0x7a, 0x65, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x73, 0x69, 0x7a, 0x65, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x70, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x72, 0x70, 0x73, 0x22,
	0x16, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x4c, 0x6f, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x62, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x31, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x4c, 0x6f, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x4c, 0x6f, 0x67, 0x52, 0x0c, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x4c, 0x6f, 0x67, 0x22, 0xd6, 0x03, 0x0a, 0x0c,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x4c, 0x6f, 0x67, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x70,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x72, 0x70, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x66, 0x61, 0x69, 0x6c, 0x52, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x66,
	0x61, 0x69, 0x6c, 0x52, 0x70, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x75, 0x73, 0x68, 0x52, 0x70, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x70,
	0x75, 0x73, 0x68, 0x52, 0x70, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x74, 0x65, 0x52,
	0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x42, 0x79, 0x74, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x79, 0x74, 0x65, 0x52, 0x61, 0x74, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x79,
	0x74, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75,
	0x73, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70,
	0x75, 0x73, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x61, 0x69, 0x6c,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x61, 0x69,
	0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x52,
	0x61, 0x74, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x52, 0x61, 0x74, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x89, 0x02, 0x0a, 0x18, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0c,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x9c, 0x01, 0x0a,
	0x10, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x70, 0x63, 0x48, 0x6f, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x70, 0x63, 0x48, 0x6f, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x70, 0x75, 0x52, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x07, 0x63, 0x70, 0x75, 0x52, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x9a, 0x03, 0x0a, 0x19,
	0x53, 0x74, 0x72, 0x65, 0x73, 0x73, 0x54, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x75, 0x74,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x65, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a,
	0x08, 0x73, 0x74, 0x6f, 0x70, 0x54, 0x65, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x53, 0x74, 0x6f, 0x70,
	0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x53, 0x74,
	0x6f, 0x70, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b,
	0x0a, 0x14, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x11, 0x70,
	0x75, 0x73, 0x68, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x15, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3e, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x4c, 0x6f, 0x67,
	0x12, 0x15, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x4c, 0x6f, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x47, 0x0a, 0x10, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x18, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x43, 0x0a, 0x20, 0x63, 0x6f, 0x6f, 0x6c,
	0x47, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x62,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x72, 0x70, 0x63, 0x42, 0x15, 0x53, 0x74,
	0x72, 0x65, 0x73, 0x73, 0x54, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x75, 0x74, 0x65, 0x72,
	0x52, 0x70, 0x63, 0x50, 0x01, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_StressTestingOuterRpc_proto_rawDescOnce sync.Once
	file_StressTestingOuterRpc_proto_rawDescData = file_StressTestingOuterRpc_proto_rawDesc
)

func file_StressTestingOuterRpc_proto_rawDescGZIP() []byte {
	file_StressTestingOuterRpc_proto_rawDescOnce.Do(func() {
		file_StressTestingOuterRpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_StressTestingOuterRpc_proto_rawDescData)
	})
	return file_StressTestingOuterRpc_proto_rawDescData
}

var file_StressTestingOuterRpc_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_StressTestingOuterRpc_proto_goTypes = []interface{}{
	(*StartTestRequest)(nil),                              // 0: StartTestRequest
	(*StartTestResponse)(nil),                             // 1: StartTestResponse
	(*StopTestRequest)(nil),                               // 2: StopTestRequest
	(*StopTestResponse)(nil),                              // 3: StopTestResponse
	(*RequestInterfaceRequest)(nil),                       // 4: RequestInterfaceRequest
	(*RequestInterfaceResponse)(nil),                      // 5: RequestInterfaceResponse
	(*PushInterfaceRequest)(nil),                          // 6: PushInterfaceRequest
	(*PushInterfaceResponse)(nil),                         // 7: PushInterfaceResponse
	(*StatisticsLogRequest)(nil),                          // 8: StatisticsLogRequest
	(*StatisticsLogResponse)(nil),                         // 9: StatisticsLogResponse
	(*StatisticLog)(nil),                                  // 10: StatisticLog
	(*WorkerServerInfoRequest)(nil),                       // 11: WorkerServerInfoRequest
	(*WorkerServerInfoResponse)(nil),                      // 12: WorkerServerInfoResponse
	(*RequestInterfaceResponse_MessageInterfaceInfo)(nil), // 13: RequestInterfaceResponse.MessageInterfaceInfo
	(*PushInterfaceResponse_MessageInterfaceInfo)(nil),    // 14: PushInterfaceResponse.MessageInterfaceInfo
	(*WorkerServerInfoResponse_WorkerServerInfo)(nil),     // 15: WorkerServerInfoResponse.WorkerServerInfo
}
var file_StressTestingOuterRpc_proto_depIdxs = []int32{
	13, // 0: RequestInterfaceResponse.interfaceInfo:type_name -> RequestInterfaceResponse.MessageInterfaceInfo
	14, // 1: PushInterfaceResponse.interfaceInfo:type_name -> PushInterfaceResponse.MessageInterfaceInfo
	10, // 2: StatisticsLogResponse.statisticLog:type_name -> StatisticLog
	15, // 3: WorkerServerInfoResponse.workerServer:type_name -> WorkerServerInfoResponse.WorkerServerInfo
	0,  // 4: StressTestingOuterService.startTest:input_type -> StartTestRequest
	2,  // 5: StressTestingOuterService.stopTest:input_type -> StopTestRequest
	4,  // 6: StressTestingOuterService.requestInterfaceInfo:input_type -> RequestInterfaceRequest
	6,  // 7: StressTestingOuterService.pushInterfaceInfo:input_type -> PushInterfaceRequest
	8,  // 8: StressTestingOuterService.statisticsLog:input_type -> StatisticsLogRequest
	11, // 9: StressTestingOuterService.workerServerInfo:input_type -> WorkerServerInfoRequest
	1,  // 10: StressTestingOuterService.startTest:output_type -> StartTestResponse
	3,  // 11: StressTestingOuterService.stopTest:output_type -> StopTestResponse
	5,  // 12: StressTestingOuterService.requestInterfaceInfo:output_type -> RequestInterfaceResponse
	7,  // 13: StressTestingOuterService.pushInterfaceInfo:output_type -> PushInterfaceResponse
	9,  // 14: StressTestingOuterService.statisticsLog:output_type -> StatisticsLogResponse
	12, // 15: StressTestingOuterService.workerServerInfo:output_type -> WorkerServerInfoResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_StressTestingOuterRpc_proto_init() }
func file_StressTestingOuterRpc_proto_init() {
	if File_StressTestingOuterRpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_StressTestingOuterRpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartTestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StressTestingOuterRpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartTestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StressTestingOuterRpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopTestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StressTestingOuterRpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopTestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StressTestingOuterRpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestInterfaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StressTestingOuterRpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestInterfaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StressTestingOuterRpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushInterfaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StressTestingOuterRpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushInterfaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StressTestingOuterRpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticsLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StressTestingOuterRpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticsLogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StressTestingOuterRpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StressTestingOuterRpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerServerInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StressTestingOuterRpc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerServerInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StressTestingOuterRpc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestInterfaceResponse_MessageInterfaceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StressTestingOuterRpc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushInterfaceResponse_MessageInterfaceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StressTestingOuterRpc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerServerInfoResponse_WorkerServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_StressTestingOuterRpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_StressTestingOuterRpc_proto_goTypes,
		DependencyIndexes: file_StressTestingOuterRpc_proto_depIdxs,
		MessageInfos:      file_StressTestingOuterRpc_proto_msgTypes,
	}.Build()
	File_StressTestingOuterRpc_proto = out.File
	file_StressTestingOuterRpc_proto_rawDesc = nil
	file_StressTestingOuterRpc_proto_goTypes = nil
	file_StressTestingOuterRpc_proto_depIdxs = nil
}
